name: Flutter checks

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  linting:
    name: Linting & Formatting
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch version info
        run: |
          # Extract flutter_version from .fvmrc
          FLUTTER_VERSION=$(jq -r '.flutter' .fvmrc)
          echo "FLUTTER_VERSION=${FLUTTER_VERSION}" >> "$GITHUB_ENV"
        shell: bash

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      - name: Get dependencies
        run: flutter pub get

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Analyze Flutter
        uses: ValentinVignal/action-dart-analyze@v2.0
        with:
          emojis: false
          fail-on: info
          line-length: 120
